steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/konyangschedulemaster/konyang-schedule'  # 프로젝트 ID 사용
      - '.'
images:
  - 'gcr.io/konyangschedulemaster/konyang-schedule'  # 동일한 이미지 URL
