steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/ksmrun/konyang-schedule'  # 프로젝트 ID 사용
      - '.'
images:
  - 'gcr.io/ksmrun/konyang-schedule'  # 동일한 이미지 URL

options:
  logging: CLOUD_LOGGING_ONLY  # 로그를 Cloud Logging에만 저장하도록 설정 (기본값)
